In [3]:
#Create a null vector of size 10 but the fifth value which is 1
import numpy as np

b=np.array([int(x==4) for x in range(10)])
print(b)




[0 0 0 0 1 0 0 0 0 0]


In [4]:
# Create a vector with values ranging from 10 to 49.
import numpy as np
v = np.arange(10,49)

print(v)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34
 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [10]:
#Create a 3x3 matrix with values ranging from 0 to 8
import numpy as np
x =  np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [13]:
# Find indices of non-zero elements from [1,2,0,0,4,0]
d = np.array([1, 2, 0, 0, 4, 0])

np.nonzero(d)

(array([0, 1, 4], dtype=int64),)

In [9]:
#Create a 10x10 array with random values and find the minimum and maximum values.
import numpy as np
x = np.random.random((10,10))

print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)

[[  3.57760585e-01   4.98473022e-01   9.70559701e-01   8.23410487e-01
    2.85412214e-01   7.12820564e-01   2.88914615e-01   9.86235923e-01
    9.25070706e-03   9.49277330e-01]
 [  7.47658551e-01   1.42820201e-01   4.22754443e-02   4.77152832e-01
    2.18992691e-01   5.37669567e-01   4.47544610e-01   5.50856023e-01
    5.32047700e-01   4.61180462e-02]
 [  5.63736085e-01   6.65748080e-01   7.18055371e-01   6.63604400e-01
    2.45065019e-01   7.35020181e-01   2.75073478e-02   6.27510248e-01
    1.44896718e-01   6.84719771e-02]
 [  5.99437426e-01   5.39152509e-01   5.95313617e-01   6.80909500e-01
    4.03609888e-01   2.22986245e-01   5.89122374e-01   2.36618413e-01
    8.62989705e-02   1.89212644e-01]
 [  2.23997851e-01   6.12075279e-01   9.51912582e-01   9.06809633e-01
    6.97323473e-01   4.69706549e-01   6.23456969e-04   7.99898467e-01
    3.07477362e-01   6.99129488e-01]
 [  3.28075491e-01   1.61523958e-01   2.73937746e-01   2.87642104e-01
    9.19565831e-01   5.33960970e-01   7.96314

In [11]:
# Create a random vector of size 30 and find the mean value.
f = np.random.random((5,6))

print(f)

np.mean(f)

[[ 0.3049263   0.09562031  0.83132177  0.67145209  0.77249729  0.76218758]
 [ 0.27196183  0.43666214  0.35284329  0.55593964  0.32361824  0.22766552]
 [ 0.14351666  0.32414057  0.52400144  0.30896991  0.64470061  0.01830127]
 [ 0.30546083  0.26663153  0.39110122  0.75268421  0.00991975  0.76484766]
 [ 0.20566415  0.7313805   0.02852312  0.30818415  0.25141895  0.9114178 ]]


0.41658534496713368